# Generated by Django 5.0.6 on 2024-06-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder',
            name='type_acot',
            field=models.CharField(choices=[('P', 'Personal'), ('F', 'Familiar')], default='P', max_length=1),
        ),
    ]
