# Generated by Django 5.0.7 on 2024-07-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finders', '0002_alter_finder_type_acot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finder',
            name='email',
            field=models.EmailField(default=str, max_length=254, unique=True),
        ),
    ]
