# Generated by Django 5.1.1 on 2024-09-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=str, max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('type_acot', models.CharField(choices=[('P', 'Personal'), ('F', 'Familiar')], default='P', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Activado'), ('D', 'Desactivado')], default='A', max_length=1)),
                ('ivr', models.CharField(max_length=20)),
                ('months', models.TextField()),
                ('consul', models.TextField()),
                ('cas', models.TextField()),
            ],
        ),
    ]
