# Generated by Django 5.0.6 on 2024-06-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ivr',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(max_length=1),
        ),
    ]
