# Generated by Django 5.0.6 on 2024-06-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_ivr_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('A', 'Activado'), ('D', 'Desactivado')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='type_acot',
            field=models.CharField(choices=[('P', 'Personal'), ('F', 'Familiar')], default='P', max_length=1),
        ),
    ]
