# Generated by Django 5.0.6 on 2024-06-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_status_alter_account_type_acot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='date',
            new_name='consul',
        ),
    ]
