# Generated by Django 5.0.7 on 2024-07-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_date_account_consul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default=str, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='ivr',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
