# Generated by Django 5.1.1 on 2024-09-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_search', models.CharField(choices=[('P', 'Personal'), ('F', 'Familiar'), ('G', 'General'), ('D', 'Desactivado')], default='G', max_length=1)),
                ('find_2024', models.BooleanField(default=False)),
                ('months_2024', models.TextField(default='0')),
                ('find_2025', models.BooleanField(default=False)),
                ('months_2025', models.TextField(default='0')),
                ('timing', models.IntegerField()),
            ],
        ),
    ]
