# Generated by Django 5.0.6 on 2024-06-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_search', models.CharField(choices=[('P', 'Personal'), ('F', 'Familiar'), ('G', 'General'), ('D', 'Desactivado')], default='G', max_length=1)),
                ('timing', models.IntegerField()),
            ],
        ),
    ]
