# Generated by Django 5.0.6 on 2024-06-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='find_2024',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='find_2025',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='months_2024',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='settings',
            name='months_2025',
            field=models.TextField(default=''),
        ),
    ]
