# Generated by Django 5.0.6 on 2024-06-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_settings_find_2024_settings_find_2025_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='months_2024',
            field=models.TextField(default='0'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='months_2025',
            field=models.TextField(default='0'),
        ),
    ]
